version: '3'

services:
  frontend:
    container_name: frontend
    #env_file:
    # - .env
    image: REGISTRY/REPLACE:TAG
    ports:
      - '5173:5173'
    #environment:
    #API_URI: '\${API_URI}'
    volumes:
      - .:/persist
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
